### ISSUE TITLE
Allow user to exclude specific tiles for stichting a section

### ISSUE THREAD

**Issue by aloejhb** [fmi-basel/gfriedri-em-alignment#14]
In some sections, although a tile has been acquired, the user may not want to include this tile for stitching. Would there be a way to exlcude the tile from the already generated tile_id_map?

An example for this is the following section (s2302):
![example_section_to_delete_a_tile](https://user-images.githubusercontent.com/19688778/174065325-bad78d24-6190-4179-8301-64608cc021ee.png)
tile 517 is acquired, but does not contain the tissue of interest. Since there is charging effect on the left corner of tile 517, it was not successfully coarsely aligned with tile 516, resulting an inf offset value.
In this case, it would be nice to have an option to simply exclude tile 517.

**Comment by tibuch** [comment]
This would be a manual exclusion i.e. you know which section has a tile that you don't want to use? If this should be automated I think we first have to figure out how to classify tiles into good and bad.

If it is just manual we should consider to save the tile-id-map as e.g. json file instead of numpy-array. Then it could easily be hand edited by anyone and you would just set the tile-id to -1.

**Comment by tibuch** [comment]
Now the `tile_id_map`s are saved as json files. If you want to exclude a tile you just set it to -1 in the json file.

At least that is the theory :smile:

**Comment by aloejhb** [comment]
This is working nicely too. By replacing the tile number to -1 in the tile_id_map, the stitching excluded the tile from the section.
Thanks again for the great job!
